# -----------------------------------------------------
# Monitor Setup
# name: "3440x1440"
# -----------------------------------------------------

#monitor=,preferred,auto,auto
#monitor=DP-2,preferred,auto,auto

monitor = DP-1, 3840x2160@240.02, auto, 1
monitor = HDMI-A-1, preferred, auto, auto

