# -----------------------------------------------------
# Monitor Setup
# name: "3440x1440"
# -----------------------------------------------------
monitor=,preferred,auto,auto
monitor=DP-2,preferred,auto,auto
