# Hyprpaper configurations
preload = ~/.config/wallpapers/wp14372941-dark-ultrawide-4k-wallpapers.jpg
#wallpaper = , ~/.config/wallpapers/wp14372941-dark-ultrawide-4k-wallpapers.jpg
splash = false

wallpaper {
   monitor = DP-2
   path = ~/.config/wallpapers/wp14372941-dark-ultrawide-4k-wallpapers.jpg
   fit_mode = cover
}


wallpaper {
   monitor = DP-1
   path = ~/.config/wallpapers/wp14372941-dark-ultrawide-4k-wallpapers.jpg
   fit_mode = cover
}


