#  _   _                  _                 _
# | | | |_   _ _ __  _ __| | __ _ _ __   __| |
# | |_| | | | | '_ \| '__| |/ _` | '_ \ / _` |
# |  _  | |_| | |_) | |  | | (_| | | | | (_| |
# |_| |_|\__, | .__/|_|  |_|\__,_|_| |_|\__,_|
#        |___/|_|
#
# -----------------------------------------------------
# configurations by: qdrtech
# https://github.com/qdrtech/dotfiles

# -----------------------------------------------------
# MONITORS 
# -----------------------------------------------------
source = ~/.config/hypr/conf/monitors.conf

# -----------------------------------------------------
# PROGRAMS 
# -----------------------------------------------------
$terminal = ghostty
$fileManager = nautilus
$menu = rofi -show drun

# -----------------------------------------------------
# Cursor   
# -----------------------------------------------------
source = ~/.config/hypr/conf/cursor.conf

# -----------------------------------------------------
# AUTOSTART 
# -----------------------------------------------------
source = ~/.config/hypr/conf/autostart.conf

# -----------------------------------------------------
# ENVIRONMENT VARIABLES 
# -----------------------------------------------------
source = ~/.config/hypr/conf/environment.conf

# -----------------------------------------------------
#   Decoration  
# -----------------------------------------------------
source = ~/.config/hypr/conf/decoration.conf

# -----------------------------------------------------
#   Animation   
# -----------------------------------------------------
source = ~/.config/hypr/conf/animation.conf

# -----------------------------------------------------
#     Layout    
# -----------------------------------------------------
source = ~/.config/hypr/conf/layout.conf

# -----------------------------------------------------
#     Misc      
# -----------------------------------------------------
source = ~/.config/hypr/conf/misc.conf

# -----------------------------------------------------
#   Keybboard    
# -----------------------------------------------------
source = ~/.config/hypr/conf/keyboard.conf

# -----------------------------------------------------
# KEYBINDINGS 
# -----------------------------------------------------
source = ~/.config/hypr/conf/keybinding.conf

# -----------------------------------------------------
# WINDOWS AND WORKSPACES 
# -----------------------------------------------------
source = ~/.config/hypr/conf/layerrule.conf
source = ~/.config/hypr/conf/window.conf
source = ~/.config/hypr/conf/windowrule.conf
source = ~/.config/hypr/conf/workspace.conf
