#!/usr/bin/env bash
# Palette-first theme switcher:
# - Each theme directory only contains colors.conf (shell vars like BG, SURFACE, TEXT, ACCENT).
# - Active theme is symlinked to ~/.config/themes/current.
# - Per-app color includes are generated from the palette for Hyprland, Waybar, Rofi, Ghostty.

set -euo pipefail

DOTFILES_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
THEMES_DIR="${THEMES_DIR:-"$DOTFILES_ROOT/themes"}"
CONFIG_ROOT="${XDG_CONFIG_HOME:-$HOME/.config}"
TARGET_THEMES_ROOT="${CONFIG_ROOT}/themes"
CURRENT_LINK="${TARGET_THEMES_ROOT}/current"

HYPR_OUT="${CONFIG_ROOT}/hypr/theme-colors.conf"
WAYBAR_OUT="${CONFIG_ROOT}/waybar/theme-colors.css"
ROFI_OUT="${CONFIG_ROOT}/rofi/theme-colors.rasi"
ROFI_THEME_OUT="${CONFIG_ROOT}/rofi/generated-theme.rasi"
GHOSTTY_OUT="${CONFIG_ROOT}/ghostty/theme.conf"

log() { printf '[theme-switch] %s\n' "$*"; }
err() { printf '[theme-switch][error] %s\n' "$*" >&2; }

usage() {
  cat <<'EOF'
Usage: theme-switch.sh <command> [args]

Commands:
  list                     List available themes
  current                  Show the currently linked theme
  set [--no-reload] <name> Switch to the specified theme (reload Hyprland unless --no-reload)
  help                     Show this help message

Environment overrides:
  THEMES_DIR           Path to themes directory (default: repo/themes)
EOF
}

list_themes() {
  [ -d "$THEMES_DIR" ] || return 0
  find "$THEMES_DIR" -mindepth 1 -maxdepth 1 -type d ! -name '.*' -printf '%f\n' | sort
}

current_theme() {
  if [ -L "$CURRENT_LINK" ]; then
    basename "$(readlink -f "$CURRENT_LINK")"
  elif [ -d "$CURRENT_LINK" ]; then
    basename "$CURRENT_LINK"
  else
    echo "none"
  fi
}

hex_to_rgb() {
  # hex_to_rgb "#RRGGBB" -> "R G B"
  local hex="${1#'#'}"
  local r=${hex:0:2}
  local g=${hex:2:2}
  local b=${hex:4:2}
  printf '%d %d %d' "0x$r" "0x$g" "0x$b"
}

rgba_from_hex() {
  local hex="$1"
  local alpha="${2:-255}"
  read -r r g b <<<"$(hex_to_rgb "$hex")"
  printf 'rgba(%s, %s, %s, %s)' "$r" "$g" "$b" "$alpha"
}

load_palette() {
  local palette="$1"
  # shellcheck disable=SC1090
  source "$palette"

  # Fallbacks if some keys are missing
  : "${BG:=#1e1e2e}"
  : "${SURFACE:=#313244}"
  : "${SURFACE_ALT:=$SURFACE}"
  : "${TEXT:=#cdd6f4}"
  : "${TEXT_MUTED:=#a6adc8}"
  : "${ACCENT:=#89b4fa}"
  : "${ACCENT_ALT:=$ACCENT}"
  : "${WARN:=#f9e2af}"
  : "${ERROR:=#f38ba8}"
  : "${SUCCESS:=#a6e3a1}"
}

hex_with_alpha() {
  local hex="${1#'#'}"
  local alpha="${2:-ff}"
  echo "0x${alpha}${hex}"
}

write_atomic() {
  # write_atomic <dest> (reads content from stdin)
  local dest="$1"
  local tmp
  tmp="$(mktemp "${dest}.XXXX")"
  cat >"$tmp"
  mkdir -p "$(dirname "$dest")"
  mv "$tmp" "$dest"
}

write_hypr() {
  write_atomic "$HYPR_OUT" <<EOF
# Generated by theme-switch.sh
\$bg = $(hex_with_alpha "$BG")
\$surface = $(hex_with_alpha "$SURFACE")
\$surface_alt = $(hex_with_alpha "$SURFACE_ALT")
\$fg = $(hex_with_alpha "$TEXT")
\$fg_muted = $(hex_with_alpha "$TEXT_MUTED")
\$accent = $(hex_with_alpha "$ACCENT")
\$accent_alt = $(hex_with_alpha "$ACCENT_ALT")
\$warn = $(hex_with_alpha "$WARN")
\$error = $(hex_with_alpha "$ERROR")
\$success = $(hex_with_alpha "$SUCCESS")
EOF
  log "wrote Hyprland colors -> $HYPR_OUT"
}

write_waybar() {
  write_atomic "$WAYBAR_OUT" <<EOF
/* Generated by theme-switch.sh */
:root {
  --bg: $BG;
  --surface: $SURFACE;
  --surface-alt: $SURFACE_ALT;
  --text: $TEXT;
  --text-muted: $TEXT_MUTED;
  --accent: $ACCENT;
  --accent-alt: $ACCENT_ALT;
  --warn: $WARN;
  --error: $ERROR;
  --success: $SUCCESS;
}
EOF
  log "wrote Waybar colors -> $WAYBAR_OUT"
}

write_rofi() {
  write_atomic "$ROFI_OUT" <<EOF
/* Generated by theme-switch.sh */
@bg: $BG;
@surface: $SURFACE;
@surface_alt: $SURFACE_ALT;
@fg: $TEXT;
@fg_muted: $TEXT_MUTED;
@accent: $ACCENT;
@accent_alt: $ACCENT_ALT;
@warn: $WARN;
@error: $ERROR;
@success: $SUCCESS;
EOF
  write_atomic "$ROFI_THEME_OUT" <<EOF
/* Generated by theme-switch.sh */
* {
    background-color: $BG;
    text-color: $TEXT;
    font: "JetBrainsMono Nerd Font 11";
}

window {
    background-color: $SURFACE;
    border: 1px;
    border-color: $ACCENT;
    padding: 12px;
    width: 600px;
}

mainbox {
    padding: 8px;
}

listview {
    lines: 8;
    spacing: 4px;
    scrollbar: false;
}

element {
    padding: 8px 10px;
    spacing: 8px;
}

element normal.normal {
    background-color: transparent;
    text-color: $TEXT;
}

element selected.normal {
    background-color: $ACCENT;
    text-color: #0b1221;
}

element-icon {
    size: 18px;
}
EOF
  log "wrote Rofi colors -> $ROFI_OUT"
  log "wrote Rofi theme  -> $ROFI_THEME_OUT"
}

write_ghostty() {
  write_atomic "$GHOSTTY_OUT" <<EOF
# Generated by theme-switch.sh
background=$BG
foreground=$TEXT
cursor-color=$ACCENT
selection-background=$SURFACE_ALT
selection-foreground=$TEXT
palette=0=$BG
palette=1=$ERROR
palette=2=$SUCCESS
palette=3=$WARN
palette=4=$ACCENT
palette=5=$ACCENT_ALT
palette=6=$ACCENT_ALT
palette=7=$TEXT
palette=8=$SURFACE
palette=9=$ERROR
palette=10=$SUCCESS
palette=11=$WARN
palette=12=$ACCENT
palette=13=$ACCENT_ALT
palette=14=$ACCENT_ALT
palette=15=$TEXT
EOF
  log "wrote Ghostty colors -> $GHOSTTY_OUT"
}

render_all() {
  local palette="$1"
  load_palette "$palette"
  write_hypr
  write_waybar
  write_rofi
  write_ghostty
}

hypr_reload() {
  if [ "${NO_HYPR_RELOAD:-0}" = "1" ]; then
    log "skipping Hypr reload (NO_HYPR_RELOAD=1)"
    return
  fi
  if command -v hyprctl >/dev/null 2>&1 && [ -n "${HYPRLAND_INSTANCE_SIGNATURE:-}" ]; then
    hyprctl reload >/dev/null 2>&1 && log "Hyprland reloaded" || log "Hyprland reload failed"
  else
    log "Hyprland not detected; skipping reload"
  fi
}

set_theme() {
  local reload=1
  if [ "${1:-}" = "--no-reload" ]; then
    reload=0
    shift
  fi
  local theme="$1"
  local theme_path="$THEMES_DIR/$theme"

  [ -n "$theme" ] || { err "no theme name provided"; usage; exit 1; }
  [ -d "$theme_path" ] || { err "theme '$theme' not found in $THEMES_DIR"; exit 1; }

  mkdir -p "$TARGET_THEMES_ROOT"
  ln -sfn "$theme_path" "$CURRENT_LINK"
  log "activated theme '$theme' ($theme_path)"

  if [ ! -f "$CURRENT_LINK/colors.conf" ]; then
    err "colors.conf missing in theme '$theme'"
    exit 1
  fi

  ln -sfn "$CURRENT_LINK/colors.conf" "$TARGET_THEMES_ROOT/colors.conf"
  render_all "$CURRENT_LINK/colors.conf"

  echo "$theme" > "$TARGET_THEMES_ROOT/current.txt"
  log "theme name recorded at $TARGET_THEMES_ROOT/current.txt"
  [ "$reload" -eq 1 ] && hypr_reload
}

cmd="${1:-help}"
case "$cmd" in
  list) list_themes ;;
  current) current_theme ;;
  set) shift; set_theme "$@" ;;
  help|--help|-h) usage ;;
  *) err "unknown command: $cmd"; usage; exit 1 ;;
esac
