#!/usr/bin/env bash
# Palette-first theme switcher:
# - Each theme directory only contains colors.conf (shell vars like BG, SURFACE, TEXT, ACCENT).
# - Active theme is symlinked to ~/.config/themes/current.
# - Per-app color includes are generated from the palette for Hyprland, Waybar,
#   Rofi, Ghostty, SwayNC and Starship.

set -euo pipefail

DOTFILES_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
THEMES_DIR="${THEMES_DIR:-"$DOTFILES_ROOT/themes/.config/themes"}"
CONFIG_ROOT="${XDG_CONFIG_HOME:-$HOME/.config}"
TARGET_THEMES_ROOT="${CONFIG_ROOT}/themes"
CURRENT_LINK="${TARGET_THEMES_ROOT}/current"

HYPR_OUT="${CONFIG_ROOT}/hypr/theme-colors.conf"
WAYBAR_OUT="${CONFIG_ROOT}/waybar/theme-colors.css"
ROFI_OUT="${CONFIG_ROOT}/rofi/theme-colors.rasi"
ROFI_THEME_OUT="${CONFIG_ROOT}/rofi/generated-theme.rasi"
GHOSTTY_OUT="${CONFIG_ROOT}/ghostty/theme.conf"
SWAYNC_OUT="${CONFIG_ROOT}/swaync/theme-colors.css"
STARSHIP_OUT="${CONFIG_ROOT}/starship.toml"

GENERATED_MARKER='Generated by theme-switch.sh'

log() { printf '[theme-switch] %s\n' "$*"; }
err() { printf '[theme-switch][error] %s\n' "$*" >&2; }

usage() {
  cat <<'EOF'
Usage: theme-switch.sh <command> [args]

Commands:
  list                     List available themes
  current                  Show the currently linked theme
  set [--no-reload] <name> Switch to the specified theme (reload Hyprland unless --no-reload)
  help                     Show this help message

Environment overrides:
  THEMES_DIR           Path to themes directory (default: repo/themes/.config/themes)
EOF
}

list_themes() {
  [ -d "$THEMES_DIR" ] || return 0
  find "$THEMES_DIR" -mindepth 1 -maxdepth 1 -type d ! -name '.*' ! -name current -printf '%f\n' | sort
}

current_theme() {
  # A symlink that does not resolve is not a current theme -- report none rather
  # than the basename of a dangling target.
  if [ -L "$CURRENT_LINK" ] && [ -e "$CURRENT_LINK" ]; then
    basename "$(readlink -f "$CURRENT_LINK")"
  elif [ ! -L "$CURRENT_LINK" ] && [ -d "$CURRENT_LINK" ]; then
    basename "$CURRENT_LINK"
  else
    echo "none"
  fi
}

hex_to_rgb() {
  # hex_to_rgb "#RRGGBB" -> "R G B"
  local hex="${1#'#'}"
  local r=${hex:0:2}
  local g=${hex:2:2}
  local b=${hex:4:2}
  printf '%d %d %d' "0x$r" "0x$g" "0x$b"
}

rgba_from_hex() {
  local hex="$1"
  local alpha="${2:-255}"
  read -r r g b <<<"$(hex_to_rgb "$hex")"
  printf 'rgba(%s, %s, %s, %s)' "$r" "$g" "$b" "$alpha"
}

load_palette() {
  local palette="$1"
  # shellcheck disable=SC1090
  source "$palette"

  # Fallbacks if some keys are missing
  : "${BG:=#1e1e2e}"
  : "${SURFACE:=#313244}"
  : "${SURFACE_ALT:=$SURFACE}"
  : "${TEXT:=#cdd6f4}"
  : "${TEXT_MUTED:=#a6adc8}"
  : "${ACCENT:=#89b4fa}"
  : "${ACCENT_ALT:=$ACCENT}"
  : "${WARN:=#f9e2af}"
  : "${ERROR:=#f38ba8}"
  : "${SUCCESS:=#a6e3a1}"
}

hex_with_alpha() {
  local hex="${1#'#'}"
  local alpha="${2:-ff}"
  echo "0x${alpha}${hex}"
}

write_atomic() {
  # write_atomic <dest> (reads content from stdin)
  local dest="$1"
  local tmp
  # The destination directory has to exist before mktemp can create the
  # temporary file inside it.
  mkdir -p "$(dirname "$dest")"
  tmp="$(mktemp "${dest}.XXXX")"
  cat >"$tmp"
  mv "$tmp" "$dest"
}

write_hypr() {
  write_atomic "$HYPR_OUT" <<EOF
# Generated by theme-switch.sh
\$bg = $(hex_with_alpha "$BG")
\$surface = $(hex_with_alpha "$SURFACE")
\$surface_alt = $(hex_with_alpha "$SURFACE_ALT")
\$fg = $(hex_with_alpha "$TEXT")
\$fg_muted = $(hex_with_alpha "$TEXT_MUTED")
\$accent = $(hex_with_alpha "$ACCENT")
\$accent_alt = $(hex_with_alpha "$ACCENT_ALT")
\$warn = $(hex_with_alpha "$WARN")
\$error = $(hex_with_alpha "$ERROR")
\$success = $(hex_with_alpha "$SUCCESS")
EOF
  log "wrote Hyprland colors -> $HYPR_OUT"
}

write_waybar() {
  write_atomic "$WAYBAR_OUT" <<EOF
/* Generated by theme-switch.sh */
@define-color bg $BG;
@define-color surface $SURFACE;
@define-color surface-alt $SURFACE_ALT;
@define-color text $TEXT;
@define-color text-muted $TEXT_MUTED;
@define-color accent $ACCENT;
@define-color accent-alt $ACCENT_ALT;
@define-color warn $WARN;
@define-color error $ERROR;
@define-color success $SUCCESS;
EOF
  log "wrote Waybar colors -> $WAYBAR_OUT"
}

write_rofi() {
  # Rofi 2.0 rejects the top-level "@name: value;" form and rejects underscores
  # in property names. Palette entries have to live in a "* { }" block and use
  # hyphens; references stay "@name".
  write_atomic "$ROFI_OUT" <<EOF
/* Generated by theme-switch.sh */
* {
    bg:          $BG;
    surface:     $SURFACE;
    surface-alt: $SURFACE_ALT;
    fg:          $TEXT;
    fg-muted:    $TEXT_MUTED;
    accent:      $ACCENT;
    accent-alt:  $ACCENT_ALT;
    warn:        $WARN;
    error:       $ERROR;
    success:     $SUCCESS;

    /* Aliases for the names config.rasi references. */
    background:  @bg;
    foreground:  @fg;
    color11:     @accent;
}
EOF
  write_atomic "$ROFI_THEME_OUT" <<EOF
/* Generated by theme-switch.sh */
@import "theme-colors.rasi"

* {
    background-color: @bg;
    text-color:       @fg;
    font:             "JetBrainsMono Nerd Font 11";
}

window {
    background-color: @surface;
    border:           1px;
    border-color:     @accent;
    padding:          12px;
    width:            600px;
}

mainbox {
    padding: 8px;
}

listview {
    lines:     8;
    spacing:   4px;
    scrollbar: false;
}

element {
    padding: 8px 10px;
    spacing: 8px;
}

element normal.normal {
    background-color: transparent;
    text-color:       @fg;
}

element selected.normal {
    background-color: @accent;
    text-color:       @bg;
}

element-icon {
    size: 18px;
}
EOF
  log "wrote Rofi colors -> $ROFI_OUT"
  log "wrote Rofi theme  -> $ROFI_THEME_OUT"
}

write_ghostty() {
  write_atomic "$GHOSTTY_OUT" <<EOF
# Generated by theme-switch.sh
background=$BG
foreground=$TEXT
cursor-color=$ACCENT
selection-background=$SURFACE_ALT
selection-foreground=$TEXT
palette=0=$BG
palette=1=$ERROR
palette=2=$SUCCESS
palette=3=$WARN
palette=4=$ACCENT
palette=5=$ACCENT_ALT
palette=6=$ACCENT_ALT
palette=7=$TEXT
palette=8=$SURFACE
palette=9=$ERROR
palette=10=$SUCCESS
palette=11=$WARN
palette=12=$ACCENT
palette=13=$ACCENT_ALT
palette=14=$ACCENT_ALT
palette=15=$TEXT
EOF
  log "wrote Ghostty colors -> $GHOSTTY_OUT"
}

write_swaync() {
  write_atomic "$SWAYNC_OUT" <<EOF
/* Generated by theme-switch.sh */
@define-color bg $BG;
@define-color surface $SURFACE;
@define-color surface-alt $SURFACE_ALT;
@define-color text $TEXT;
@define-color text-muted $TEXT_MUTED;
@define-color accent $ACCENT;
@define-color accent-alt $ACCENT_ALT;
@define-color warn $WARN;
@define-color error $ERROR;
@define-color success $SUCCESS;
EOF
  log "wrote SwayNC colors -> $SWAYNC_OUT"
}

write_starship() {
  # The file-first switcher symlinked the theme's own starship.toml here. The
  # palette-first equivalent generates it, so back up an authored config once
  # before the first overwrite.
  # Guard on existence rather than "regular file that is not a symlink": the old
  # test skipped the backup in exactly the cases that need it. A symlinked
  # starship.toml (what the file-first switcher left behind) failed "! -L", and a
  # stowed one would pass "-f" through the link while still failing "! -L" -- in
  # both cases the write below replaces the link with no copy taken. "-e"
  # follows the link, so it is true whenever there is content to preserve and
  # false for a dangling link, which has none.
  if [ -e "$STARSHIP_OUT" ] \
     && ! head -n 1 "$STARSHIP_OUT" | grep -q "$GENERATED_MARKER"; then
    local backup="${STARSHIP_OUT}.backup-$(date +%Y%m%d-%H%M%S)"
    cp "$STARSHIP_OUT" "$backup"
    log "backed up existing Starship config -> $backup"
  fi

  write_atomic "$STARSHIP_OUT" <<EOF
# Generated by theme-switch.sh
format = """
\$username\$directory\$git_branch\$git_status\$fill\$python\$lua\$nodejs\$golang\$package\$aws\$docker_context\$jobs\$time\$cmd_duration\$line_break
[╰─](text)\$character """

add_newline = true
palette = "theme"

[palettes.theme]
bg = "$BG"
surface = "$SURFACE"
surface_alt = "$SURFACE_ALT"
text = "$TEXT"
text_muted = "$TEXT_MUTED"
accent = "$ACCENT"
accent_alt = "$ACCENT_ALT"
warn = "$WARN"
error = "$ERROR"
success = "$SUCCESS"

[username]
show_always = true
style_root = 'bold fg:error'
style_user = 'bold fg:warn'

[directory]
read_only = "🔒"
style = 'bold fg:accent'
format = '[\$path ](\$style)'
truncation_length = 3
truncation_symbol = ''
truncate_to_repo = true

[directory.substitutions]
'Documents' = '󰈙'
'Downloads' = ' '
'Music' = ' '
'Pictures' = ' '

[git_branch]
style = 'fg:error'
symbol = ' '
format = '[on](text) [\$symbol\$branch ](\$style)'

[git_state]

[git_status]
style = 'fg:success'
format = '([\$all_status\$ahead_behind](\$style) )'

[fill]
symbol = ' '

[package]
format = 'via [🎁 \$version](warn bold) '

[python]
style = 'accent_alt'
symbol = ' '
format = '[\${symbol}\${pyenv_prefix}(\${version} )(\\(\$virtualenv\\) )](\$style)'
pyenv_version_name = true
pyenv_prefix = ''

[lua]
symbol = ' '

[nodejs]
style = 'accent'
symbol = ' '
format = 'via [\$symbol(\$version )](\$style)'

[bun]
symbol = '🍔 '
style = 'success'
format = 'via [\$style](\$style) '

[golang]
style = 'accent'
symbol = ' '

[haskell]
style = 'accent'
symbol = ' '

[rust]
style = 'warn'
symbol = ' '

[ruby]
style = 'accent'
symbol = ' '

[aws]
symbol = ' '
style = 'warn'
format = '[\$symbol(\$profile )(\\[\$duration\\] )](\$style)'

[docker_context]
symbol = ' '
style = 'fg:accent_alt'
format = '[\$symbol](\$style) \$path'
detect_files = ['docker-compose.yml', 'docker-compose.yaml', 'Dockerfile']
detect_extensions = ['Dockerfile']

[jobs]
symbol = '✦'
style = 'error'
number_threshold = 1
format = '[\$symbol](\$style)'

[character]
format = "\$symbol"
success_symbol = "[❯](bold success)"
error_symbol = "[✗](bold error) "
vicmd_symbol = "[❮](bold success)"
disabled = false

[cmd_duration]
show_milliseconds = false
style = "bold warn"
format = "took [\$duration](\$style)"

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
format = '[  \$time ](\$style)'
EOF
  log "wrote Starship config -> $STARSHIP_OUT"
}

render_all() {
  local palette="$1"
  load_palette "$palette"
  write_hypr
  write_waybar
  write_rofi
  write_ghostty
  write_swaync
  write_starship
}

hypr_reload() {
  if [ "${NO_HYPR_RELOAD:-0}" = "1" ]; then
    log "skipping Hypr reload (NO_HYPR_RELOAD=1)"
    return
  fi
  if command -v hyprctl >/dev/null 2>&1 && [ -n "${HYPRLAND_INSTANCE_SIGNATURE:-}" ]; then
    hyprctl reload >/dev/null 2>&1 && log "Hyprland reloaded" || log "Hyprland reload failed"
  else
    log "Hyprland not detected; skipping reload"
  fi
}

swaync_reload() {
  if command -v swaync-client >/dev/null 2>&1; then
    swaync-client --reload-config >/dev/null 2>&1 || true
    swaync-client --reload-css >/dev/null 2>&1 || true
    log "SwayNC reloaded"
  else
    log "swaync-client not found; skipping SwayNC reload"
  fi
}

set_theme() {
  local reload=1
  if [ "${1:-}" = "--no-reload" ]; then
    reload=0
    shift
  fi
  local theme="${1:-}"
  local theme_path="$THEMES_DIR/$theme"

  [ -n "$theme" ] || { err "no theme name provided"; usage; exit 1; }
  [ -d "$theme_path" ] || { err "theme '$theme' not found in $THEMES_DIR"; exit 1; }

  mkdir -p "$TARGET_THEMES_ROOT"
  ln -sfn "$theme_path" "$CURRENT_LINK"
  log "activated theme '$theme' ($theme_path)"

  if [ ! -f "$CURRENT_LINK/colors.conf" ]; then
    err "colors.conf missing in theme '$theme'"
    exit 1
  fi

  ln -sfn "$CURRENT_LINK/colors.conf" "$TARGET_THEMES_ROOT/colors.conf"
  render_all "$CURRENT_LINK/colors.conf"

  echo "$theme" > "$TARGET_THEMES_ROOT/current.txt"
  log "theme name recorded at $TARGET_THEMES_ROOT/current.txt"

  if [ "$reload" -eq 1 ]; then
    hypr_reload
    swaync_reload
  fi
  return 0
}

cmd="${1:-help}"
case "$cmd" in
  list) list_themes ;;
  current) current_theme ;;
  set) shift; set_theme "$@" ;;
  help|--help|-h) usage ;;
  *) err "unknown command: $cmd"; usage; exit 1 ;;
esac
