# TMUX CONFIGURATION

###### Load Plugins ######
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'		#  Restore sessions
set -g @plugin 'tmux-plugins/tmux-continuum'		#  Auto Save and Restore sessions


# Restore using tmux-continuum
set -g @continuum-restore 'on'


# Configuration management.

	# Reload configuration file.
	bind r source-file ~/dotfiles/tmux/.tmux.conf \; display "tmux: reloaded"

# Shell management
	# Use zsh as default Shell
	set -g default-shell /usr/bin/zsh


# Mouse management.
	# enable mouse support
	set -g mouse on


# Keyboard Managment.
	# Dont wait for escape sequence after hitting
	# ESC key 
	# Fixes dealy when existing invert mode
	set -sg escape-time 0

	# Keyboar remaps
	# use C-a as preifx
	unbind C-b
	set-option -g prefix C-a
	bind C-a send-prefix


	# split planes using | and -
	bind | split-window -h
	bind - split-window -v
	unbind '"'
	unbind %



# Window Management..
	# Enable window renaming
	set-option -g allow-rename on

	# window navigation using alt-h/j/k/l
	bind -n M-h select-pane -L
	bind -n m-j select-pane -D
	bind -n M-k select-pane -U
	bind -n M-l select-pane -R


###### Load Plugins ######
run -b ~/.tmux/plugins/tpm/tpm
